language: python
python:
  - "3.6"
cache: pip
install:
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision pytest pytest-cov coveralls
  - pip install -e .
script:
  - pytest tests --cov=pytorch_refinenet
after_success:
  - coveralls
